#!/usr/bin/env python3
"""dashboard_sync.py - regenerate the generated blocks of <vault>/00-Dashboard.md from the vault state.

Part of the IT Department skill (references/contracts-and-lifecycle.md section 4,
workflows/session-protocol.md). The dashboard is generated, not hand-edited: the text between
`<!-- sync:<name> start -->` and `<!-- sync:<name> end -->` is rebuilt from the notes, reports and config
on every run; everything outside the markers (manual notes, extra sections) is left exactly as it is.
Every task/bug id, ADR, report and document is rendered as a link: a wikilink only when its target resolves
by file name inside the vault (the rule of vault_lint.py VL006), a relative markdown link for other existing
files, and plain text with "(missing)" plus a warning when the target does not exist.

Usage:
  python3 dashboard_sync.py [--root PROJECT_ROOT] [--check] [--quiet]

  --root    project root holding .it-department/config.json (default: current directory)
  --check   compare only: exit 0 when the dashboard is current, 1 when it differs (a unified diff of at
            most 60 lines is printed); never writes
  --quiet   print only the dashboard path and the summary line

Blocks: header, tokens, kanban, tasks, bugs, adr, usage-audits, content-reviews, releases, documents.
A dashboard without markers (older projects) gets every missing block inserted after its matching "## "
heading; a block whose heading is missing is appended as a new section before the Obsidian tip
("inserted block <name>"). A missing dashboard is created from assets/vault-template/00-Dashboard.md.
The file is written only when its content changes ("Last Updated" alone never counts as a change),
as UTF-8 with LF line endings.

Inputs (paths from <root>/.it-department/config.json; all optional):
  <vault>/01-Tasks/**, 02-Bugs/, 03-ADR/, 04-Archive/{Completed-Tasks,Resolved-Bugs}/   note frontmatter
  <efficiency.reports_path>/usage-audit-<date>.json + .md     tokens and usage-audits blocks
  <content_review.reports_path>/content-review-*.md           content-reviews block (frontmatter)
  <reports>/qa-report-*.md                                     releases "Verified By", documents block
  <root>/.it-department/lock.json                              header "Session Lock"
  config: project_name, cto_mode, operating_profile, documents[], efficiency.audit_interval_days and
          rules, content_review.glossary_path / style_guide_path, paths.vault_relative_path
Rule statuses R1-R5 are read from section 4 of the audit report when it has the indicator table, else
derived from the .json sidecar with the rules of usage_report.py (R1/R2 on window totals, R3 n/a).

Exit codes: 0 ok, 1 --check found differences or a block has broken markers, 2 bad arguments (no vault
at the resolved path). Requires Python 3.8+, standard library only.
"""
import argparse
import datetime
import difflib
import json
import os
import re
import stat
import sys
import tempfile

DASHBOARD = '00-Dashboard.md'
DEFAULT_REPORTS_PATH = os.path.join('vault', '05-Reports')
TASK_STATUSES = ('Backlog', 'In-Analysis', 'Ready-For-Dev', 'In-Development', 'Code-Review', 'QA-Testing', 'Ready-For-Release')
TASK_ORDER = ('In-Development', 'Code-Review', 'QA-Testing', 'Ready-For-Release', 'Ready-For-Dev', 'In-Analysis', 'Backlog')
PRIORITY_ORDER = ('critical', 'high', 'medium', 'low')
SEVERITY_RANK = {'critical': 0, 'blocker': 0, 'major': 1, 'high': 1, 'minor': 2, 'medium': 2, 'trivial': 3, 'low': 3}
PROFILES = ('prototype', 'pilot', 'production')
RULES = ('R1', 'R2', 'R3', 'R4', 'R5')
STATUS_RANK = {'n/a': 0, 'OK': 1, 'CHECK': 2}
DEFAULT_RULES = {
    'R1_builds_per_fix_round_max': 2,
    'R2_screenshots_per_scenario_max': 10,
    'R2_screenshot_scale': 0.5,
    'R4_log_tail_lines': 40,
    'R4_tool_result_tokens_max': 2000,
    'R5_queue_wait_minutes_max': 5,
}
DIFF_LIMIT = 60
MAX_ROWS = 10
DASH = '\N{EM DASH}'               # empty table cell; separator before a note
SEP = ' \N{MIDDLE DOT} '           # between facts on one line
VS16 = '\N{VARIATION SELECTOR-16}'  # emoji presentation, as in the original template headings
URL_ESCAPES = {'%': '%25', ' ': '%20', '#': '%23', '(': '%28', ')': '%29', '<': '%3C', '>': '%3E', '|': '%7C',
               '[': '%5B', ']': '%5D'}

TITLE = '# \N{OFFICE BUILDING} Project Engineering Dashboard'
NOTE = ('<!-- Generated by scripts/dashboard_sync.py (IT Department skill): the text between sync markers is '
        'rebuilt on every run; keep manual notes outside the markers. -->')
TIP = ('> [!TIP]',
       '> **Obsidian Users:** Open the `<project_root>/vault` directory in the free [Obsidian App](https://obsidian.md) '
       'to inspect backlinks, graphs, and task workflows in real time.')
JOURNAL_LINE = 'Decisions journal: [[decisions-log]]'   # static, written only where decisions-log resolves
# (block, heading, pattern that finds the heading in older dashboards, static lines after the block)
SECTIONS = (
    ('header', None, None, ()),
    ('tokens', '## \N{HIGH VOLTAGE SIGN} Tokens & Machine Time', r'token', ()),
    ('kanban', '## \N{BAR CHART} Live Task Kanban Overview', r'kanban', ()),
    ('tasks', '## \N{ROCKET} Active Sprint Tasks', r'(active|sprint).*task', ()),
    ('bugs', '## \N{BUG} Open Defects & Bugs (`vault/02-Bugs/`)', r'defect|\bbugs?\b', ()),
    ('adr', '## \N{CLASSICAL BUILDING}' + VS16 + ' Architectural Decision Records (`vault/03-ADR/`)',
     r'architectural decision|\badrs?\b', ('', JOURNAL_LINE)),
    ('usage-audits', '## \N{CHART WITH UPWARDS TREND} Usage Audits (`vault/05-Reports/`, rules R1\N{EN DASH}R5: '
     '`workflows/efficiency-and-usage-audit.md`)', r'usage audit', ()),
    ('content-reviews', '## \N{WRITING HAND}' + VS16 + ' Content & Localization Reviews (`vault/05-Reports/`, two checkpoints: '
     '`workflows/content-review.md`)', r'content.*review|locali[sz]ation', ()),
    ('releases', '## \N{PACKAGE} Recent Production Releases (`vault/04-Archive/Completed-Tasks/`)', r'release', ()),
    ('documents', '## \N{BOOKS} Documents', r'document', ()),
)
SECTION = {s[0]: s for s in SECTIONS}
BLOCKS = tuple(s[0] for s in SECTIONS)
ANY_START_RE = re.compile(r'<!--\s*sync:[\w-]+\s+start\s*-->')
# wikilinks as vault_lint.py (VL006) reads them: [[Target]], [[Target|alias]], [[Target\|alias]] in tables,
# '#heading' ignored, resolved by file name anywhere in the vault; links inside code spans do not count
WIKILINK_RE = re.compile(r'\[\[([^\[\]\n]+?)\]\]')
INLINE_CODE_RE = re.compile(r'(`+)[^\n]*?\1')
UNLINKABLE_RE = re.compile(r'[\[\]|#^]')


def _now():
    """Local wall-clock time; the single clock of a run (patched by the tests)."""
    return datetime.datetime.now()


# --------------------------------------------------------------------------- frontmatter (stdlib, no PyYAML)
KEY_RE = re.compile(r'^([A-Za-z0-9_][A-Za-z0-9_.-]*)[ \t]*:(?:[ \t]+(.*)|[ \t]*)$')
NESTED_RE = re.compile(r'^("(?:[^"\\]|\\.)*"|\'(?:[^\']|\'\')*\'|[^:#\s][^:]*?)[ \t]*:(?:[ \t]+(.*)|[ \t]*)$')
INT_RE = re.compile(r'^[-+]?(?:0|[1-9][0-9]*)$')


def comment_start(raw):
    """Index of a YAML comment (' #' outside quotes) in a value, or -1."""
    quote, i, n = None, 0, len(raw)
    while i < n:
        ch = raw[i]
        if quote:
            if quote == '"' and ch == '\\':
                i += 2
                continue
            if ch == quote:
                if quote == "'" and i + 1 < n and raw[i + 1] == "'":
                    i += 2
                    continue
                quote = None
        elif ch in '"\'':
            before = raw[:i].rstrip()
            if not before or before[-1] in '[{,:':
                quote = ch
        elif ch == '#' and (i == 0 or raw[i - 1] in ' \t'):
            return i
        i += 1
    return -1


def strip_comment(raw):
    i = comment_start(raw)
    return (raw if i < 0 else raw[:i]).strip()


def split_items(inner):
    """Split the inside of an inline list or map on top-level commas (quotes and brackets respected)."""
    items, buf, depth, quote, i = [], '', 0, None, 0
    while i < len(inner):
        ch = inner[i]
        if quote:
            buf += ch
            if quote == '"' and ch == '\\' and i + 1 < len(inner):
                buf += inner[i + 1]
                i += 2
                continue
            if ch == quote:
                quote = None
        elif ch in '"\'' and (not buf.strip() or buf.rstrip().endswith(':')):
            quote = ch
            buf += ch
        elif ch in '[{':
            depth += 1
            buf += ch
        elif ch in ']}':
            depth -= 1
            buf += ch
        elif ch == ',' and depth == 0:
            items.append(buf.strip())
            buf = ''
        else:
            buf += ch
        i += 1
    items.append(buf.strip())
    return [x for x in items if x]


def unquote(v):
    if len(v) >= 2 and v[0] == v[-1] == '"':
        return re.sub(r'\\(["\\])', r'\1', v[1:-1])
    if len(v) >= 2 and v[0] == v[-1] == "'":
        return v[1:-1].replace("''", "'")
    return v


def parse_scalar(v):
    """Quoted string, true/false, null, integer, inline list [a, b]; anything else stays a raw string."""
    v = v.strip()
    if not v:
        return ''
    if len(v) >= 2 and v[0] == v[-1] and v[0] in '"\'':
        return unquote(v)
    if v in ('true', 'True', 'TRUE'):
        return True
    if v in ('false', 'False', 'FALSE'):
        return False
    if v in ('null', 'Null', 'NULL', '~'):
        return None
    if INT_RE.match(v):
        return int(v)
    if v[0] == '[' and v[-1] == ']':
        return [parse_scalar(x) for x in split_items(v[1:-1])]
    return v


def parse_frontmatter(text):
    """(dict, body) for text that starts with a '---' block, (None, text) otherwise.

    Supports `key: value` lines with quoted strings, booleans, integers, inline lists, block lists
    (`- item` lines under an empty key), one level of indented `key: value` pairs, and ` #` comments.
    """
    lines = text.split('\n')
    if not lines or lines[0].strip() != '---':
        return None, text
    end = next((i for i in range(1, len(lines)) if lines[i].rstrip() == '---'), None)
    if end is None:
        return None, text
    fm, i = {}, 1
    while i < end:
        m = KEY_RE.match(lines[i])
        i += 1
        if not m:
            continue
        key, raw = m.group(1), strip_comment(m.group(2) or '')
        if raw:
            fm[key] = parse_scalar(raw)
            continue
        items, nested = [], {}
        while i < end:
            line = lines[i]
            s = line.strip()
            if s and not s.startswith('#'):
                if s == '-' or s.startswith('- '):
                    items.append(parse_scalar(strip_comment(s[1:])))
                elif line[:1] in ' \t':
                    nm = NESTED_RE.match(s)
                    if nm:
                        nested[unquote(nm.group(1).strip())] = parse_scalar(strip_comment(nm.group(2) or ''))
                else:
                    break
            i += 1
        fm[key] = items if items else (nested if nested else '')
    return fm, '\n'.join(lines[end + 1:])


def inline_map(value):
    """{a: 1, b: 2} written inline in frontmatter (kept as a raw string by the parser) -> dict."""
    if isinstance(value, dict):
        return value
    s = value.strip() if isinstance(value, str) else ''
    if not (s.startswith('{') and s.endswith('}')):
        return {}
    out = {}
    for item in split_items(s[1:-1]):
        k, sep, v = item.partition(':')
        if sep:
            out[unquote(k.strip())] = parse_scalar(v)
    return out


def first_heading(body):
    for line in body.split('\n'):
        if line.startswith('# '):
            return line[2:].strip()
    return ''


# --------------------------------------------------------------------------- files and formatting helpers
def load_config(root):
    try:
        with open(os.path.join(root, '.it-department', 'config.json'), encoding='utf-8-sig') as fh:
            cfg = json.load(fh)
        return cfg if isinstance(cfg, dict) else {}
    except Exception:
        return {}


def section_of(cfg, key):
    v = cfg.get(key)
    return v if isinstance(v, dict) else {}


def read_text(path):
    """UTF-8 text with the BOM dropped and line endings normalised to LF."""
    with open(path, 'rb') as fh:
        text = fh.read().decode('utf-8', errors='replace')
    if text.startswith('\N{ZERO WIDTH NO-BREAK SPACE}'):
        text = text[1:]
    return text.replace('\r\n', '\n').replace('\r', '\n')


def write_text(path, text):
    """Atomic write (temp file + rename) as UTF-8 with LF endings, keeping the file mode."""
    folder = os.path.dirname(path) or '.'
    fd, tmp = tempfile.mkstemp(prefix='.dashboard-', suffix='.tmp', dir=folder)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(text)
        if os.path.exists(path):
            os.chmod(tmp, stat.S_IMODE(os.stat(path).st_mode))
        else:
            mask = os.umask(0)
            os.umask(mask)
            os.chmod(tmp, 0o666 & ~mask)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise


def walk_md(top):
    out = []
    if not os.path.isdir(top):
        return out
    for dp, dn, fn in os.walk(top):
        dn[:] = sorted(d for d in dn if not d.startswith('.'))
        out += [os.path.join(dp, f) for f in sorted(fn) if f.lower().endswith('.md') and not f.startswith('.')]
    return out


def fwd(path, base):
    """Path relative to base with forward slashes (absolute when on another drive)."""
    try:
        r = os.path.relpath(path, base)
    except ValueError:
        r = os.path.abspath(path)
    return r.replace(os.sep, '/')


def inside(path, folder):
    try:
        f = os.path.normcase(os.path.abspath(folder))
        return os.path.commonpath([os.path.normcase(os.path.abspath(path)), f]) == f
    except ValueError:
        return False


def id_key(value):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', str(value))]


def canon(value, choices):
    s = str(value if value is not None else '').strip().lower()
    return next((c for c in choices if c.lower() == s), None)


def text_of(value):
    if value is None:
        return ''
    if isinstance(value, list):
        return ', '.join(text_of(x) for x in value)
    if isinstance(value, bool):
        return 'true' if value else 'false'
    return str(value).replace('\n', ' ').strip()


def esc(value):
    """Table cell text: '|' escaped, empty -> em dash."""
    s = text_of(value)
    return s.replace('|', '\\|') if s else DASH


def code(value, table=True):
    s = text_of(value).replace('`', "'")
    if not s:
        return DASH
    return '`%s`' % (s.replace('|', '\\|') if table else s)


def md_text(text, table=False):
    s = str(text).replace('\\', '\\\\').replace('[', '\\[').replace(']', '\\]')
    return s.replace('|', '\\|') if table else s


def md_url(path):
    return ''.join(URL_ESCAPES.get(c, c) for c in path)


def wikilink(target, alias=None, table=False):
    if alias and alias != target:
        alias = str(alias).replace('|', '/').replace('[', '(').replace(']', ')')
        return '[[%s%s%s]]' % (target, '\\|' if table else '|', alias)
    return '[[%s]]' % target


def link_target(inner):
    """'Target#heading|alias' (or the table-escaped 'Target\\|alias') -> 'Target'."""
    target = inner.split('|', 1)[0].rstrip()
    if target.endswith('\\'):
        target = target[:-1]
    return target.split('#', 1)[0].strip()


def link_label(inner):
    """Visible text of a wikilink: its alias, else its target."""
    return inner.split('|', 1)[1].strip() if '|' in inner else link_target(inner)


def fmt(n):
    return '{:,}'.format(int(n)).replace(',', ' ')


def is_num(v):
    return isinstance(v, (int, float)) and not isinstance(v, bool)


def number(v):
    return fmt(v) if is_num(v) else 'n/a'


def delta_str(prev, cur):
    if not is_num(prev) or not is_num(cur):
        return 'n/a'
    if prev == 0:
        return '+inf' if cur else '0%'
    return '%+.0f%%' % ((cur - prev) / prev * 100)


def parse_ts(value):
    """Aware datetime from an ISO timestamp ('Z' allowed; naive = UTC), or None."""
    if not isinstance(value, str) or not value.strip():
        return None
    s = value.strip()
    if s[-1:] in ('Z', 'z'):
        s = s[:-1] + '+00:00'
    try:
        dt = datetime.datetime.fromisoformat(s)
    except ValueError:
        return None
    return dt if dt.tzinfo else dt.replace(tzinfo=datetime.timezone.utc)


def parse_date(value):
    try:
        return datetime.date.fromisoformat(str(value)[:10])
    except ValueError:
        return None


def date_in(name):
    m = re.search(r'(\d{4}-\d{2}-\d{2})', name)
    return m.group(1) if m else ''


# --------------------------------------------------------------------------- usage-audit report parsing
def md_table(text, heading_pattern):
    """(lower-case header cells, data rows) of the first table under the first heading matching the pattern."""
    rx = re.compile(heading_pattern, re.I)
    lines = text.split('\n')
    start = next((k for k, line in enumerate(lines) if line.startswith('#') and rx.search(line)), None)
    if start is None:
        return None
    rows = []
    for line in lines[start + 1:]:
        if line.startswith('#'):
            break
        s = line.strip()
        if s.startswith('|'):
            if s.endswith('|') and not s.endswith('\\|'):
                s = s[:-1]
            rows.append([c.strip() for c in re.split(r'(?<!\\)\|', s[1:])])
        elif rows:
            break
    if not rows:
        return None
    body = [r for r in rows[1:] if not re.match(r'^[\s:|-]*$', '|'.join(r))]
    return [c.lower() for c in rows[0]], body


def column(header, name):
    return next((i for i, h in enumerate(header) if h.startswith(name)), None)


def count_proposals(text):
    """(total, pending) of the 'Proposals' table: rows with a non-empty Change; pending = empty Decision."""
    t = md_table(text, r'proposals')
    if t is None:
        return 0, 0
    header, rows = t
    ci, di = column(header, 'change'), column(header, 'decision')
    total = pending = 0
    for r in rows if ci is not None else []:
        if ci < len(r) and r[ci]:
            total += 1
            if di is None or di >= len(r) or not r[di]:
                pending += 1
    return total, pending


def rule_status_from_report(text):
    """{R1..R5: OK|CHECK|n/a} from the 'Rule indicators' table of a usage audit (worst row per rule)."""
    t = md_table(text, r'rule indicators')
    if t is None:
        return {}
    header, rows = t
    ri, si = column(header, 'rule'), column(header, 'status')
    out = {}
    for r in rows if ri is not None and si is not None else []:
        if max(ri, si) >= len(r) or r[ri].upper() not in RULES:
            continue
        st = r[si].upper()
        st = 'CHECK' if st in ('CHECK', 'REVIEW') else ('OK' if st == 'OK' else 'n/a')
        rule = r[ri].upper()
        if STATUS_RANK[st] > STATUS_RANK.get(out.get(rule), -1):
            out[rule] = st
    return out


def rule_status_from_sidecar(d, rules):
    """Same rules as usage_report.py section 4, computed from the sidecar totals."""
    def n(key):
        v = d.get(key)
        return v if is_num(v) else 0

    def st(flag, available):
        return ('CHECK' if flag else 'OK') if available else 'n/a'
    jobs = n('jobs') > 0
    ledger = n('ledger_sessions') > 0 or n('weighted_total') > 0
    return {'R1': st(n('build_jobs') > rules['R1_builds_per_fix_round_max'], jobs),
            'R2': st(n('images_read') > rules['R2_screenshots_per_scenario_max'], ledger),
            'R3': 'n/a',
            'R4': st(n('tool_results_over_r4') > 0 or n('compactions') > 0, ledger),
            'R5': st(n('jobs_waited_over_max') > 0 or n('overlap_minutes') > 0, jobs)}


# --------------------------------------------------------------------------- vault model and block rendering
class Dashboard(object):
    """Scans the vault once and renders every generated block."""

    def __init__(self, root, cfg, now):
        self.root, self.cfg, self.now, self.today = root, cfg, now, now.date()
        paths, eff, cr = section_of(cfg, 'paths'), section_of(cfg, 'efficiency'), section_of(cfg, 'content_review')
        self.vault = os.path.join(root, str(paths.get('vault_relative_path') or 'vault'))
        self.path = os.path.join(self.vault, DASHBOARD)
        self.usage_dir = os.path.join(root, str(eff.get('reports_path') or DEFAULT_REPORTS_PATH))
        self.content_dir = os.path.join(root, str(cr.get('reports_path') or eff.get('reports_path') or DEFAULT_REPORTS_PATH))
        self.report_dirs = []
        for d in (self.usage_dir, self.content_dir, os.path.join(self.vault, '05-Reports')):
            if all(os.path.normcase(os.path.abspath(d)) != os.path.normcase(os.path.abspath(x)) for x in self.report_dirs):
                self.report_dirs.append(d)
        content = os.path.join(self.vault, '06-Content')
        self.glossary = os.path.join(root, str(cr['glossary_path'])) if cr.get('glossary_path') else os.path.join(content, 'glossary.md')
        self.style_guide = (os.path.join(root, str(cr['style_guide_path'])) if cr.get('style_guide_path')
                            else os.path.join(content, 'style-guide.md'))
        self.content_enabled = cr.get('enabled') is not False
        self.decisions_log = os.path.join(self.vault, '03-ADR', 'decisions-log.md')
        try:
            self.interval = max(1, int(eff.get('audit_interval_days') or 2))
        except (TypeError, ValueError):
            self.interval = 2
        self.rules = dict(DEFAULT_RULES)
        if isinstance(eff.get('rules'), dict):
            self.rules.update({k: v for k, v in eff['rules'].items() if is_num(v)})
        self.warnings = []

    def warn(self, msg):
        if msg not in self.warnings:
            self.warnings.append(msg)

    def rel(self, path):
        return fwd(path, self.root)

    # ----------------------------------------------------------------------- scanning
    def load(self, path, require_fm=True):
        try:
            text = read_text(path)
        except OSError as e:
            self.warn('unreadable note: %s (%s)' % (self.rel(path), e))
            text = ''
        fm, body = parse_frontmatter(text)
        stem = os.path.splitext(os.path.basename(path))[0]
        if fm is None and require_fm:
            self.warn('no frontmatter: %s' % self.rel(path))
        fm = fm or {}
        title = text_of(fm.get('title')) or first_heading(body) or stem
        return {'path': path, 'stem': stem, 'fm': fm, 'title': title, 'id': text_of(fm.get('id')) or stem}

    def scan(self):
        self.scan_index()
        self.scan_tasks()
        self.scan_bugs()
        self.scan_adrs()
        self.scan_archive()
        self.scan_audits()
        self.reviews = self.scan_reports([self.content_dir], r'^content-review-.*\.md$', require_fm=True)
        self.qa = self.scan_reports(self.report_dirs, r'^qa-report-.*\.md$', require_fm=False)
        self.lock_text = self.scan_lock()
        profile = self.cfg.get('operating_profile')
        if profile in (None, ''):
            self.profile_text = 'production (default)'
        else:
            self.profile_text = text_of(profile)
            if self.profile_text not in PROFILES:
                self.warn("config: unknown operating_profile '%s' (prototype, pilot or production)" % self.profile_text)
        self.journal = self.resolves('decisions-log')
        if not self.journal:
            self.warn('missing document: %s (decisions journal)' % self.rel(self.decisions_log))

    def scan_index(self):
        """Every file name in the vault the way wikilinks resolve (hidden folders and node_modules skipped)."""
        self.link_names, self.link_stems = set(), set()
        for _dp, dn, fn in os.walk(self.vault):
            dn[:] = [d for d in dn if not d.startswith('.') and d != 'node_modules']
            for f in fn:
                name = f.casefold()
                self.link_names.add(name)
                if name.endswith('.md'):
                    self.link_stems.add(name[:-3])

    def resolves(self, target):
        """True when [[target]] resolves to a file of the vault (case-insensitive, '.md' optional)."""
        t = text_of(target).casefold()
        if t.endswith('.md'):
            t = t[:-3]
        return bool(t) and not UNLINKABLE_RE.search(t) and (t in self.link_stems or t in self.link_names)

    def scan_tasks(self):
        top = os.path.join(self.vault, '01-Tasks')
        tasks, unknown = [], {}
        for path in walk_md(top):
            n = self.load(path)
            parts = fwd(path, top).split('/')
            folder = parts[0] if len(parts) > 1 else ''
            n['folder'] = canon(folder, TASK_STATUSES)
            if n['folder'] is None:
                unknown.setdefault(folder or '(no status folder)', []).append(n)
            status = n['fm'].get('status')
            n['status'] = text_of(status) or n['folder'] or ''
            if status not in (None, '') and n['folder'] and canon(status, TASK_STATUSES) != n['folder']:
                self.warn('status "%s" differs from its folder %s: %s' % (text_of(status), n['folder'], self.rel(path)))
            tasks.append(n)
        for folder, notes in sorted(unknown.items()):
            self.warn('unknown status folder: %s/%s (%d note%s)' % (
                self.rel(top), folder, len(notes), '' if len(notes) == 1 else 's'))

        def key(n):
            st = canon(n['status'], TASK_ORDER)
            pr = canon(n['fm'].get('priority'), PRIORITY_ORDER)
            return (TASK_ORDER.index(st) if st else len(TASK_ORDER),
                    PRIORITY_ORDER.index(pr) if pr else len(PRIORITY_ORDER), id_key(n['id']))
        self.tasks = sorted(tasks, key=key)

    def scan_bugs(self):
        self.all_bugs = [self.load(p) for p in walk_md(os.path.join(self.vault, '02-Bugs'))]
        open_bugs = [b for b in self.all_bugs if text_of(b['fm'].get('status')).lower() != 'archived']
        self.bugs = sorted(open_bugs, key=lambda b: (SEVERITY_RANK.get(text_of(b['fm'].get('severity')).lower(), 9), id_key(b['id'])))

    def scan_adrs(self):
        adrs = [self.load(p) for p in walk_md(os.path.join(self.vault, '03-ADR'))
                if os.path.basename(p).lower() != 'decisions-log.md']
        for a in adrs:
            m = re.match(r'(?i)^(adr-\d+)', a['stem'])
            a['alias'] = text_of(a['fm'].get('id')) or (m.group(1).upper() if m else a['stem'])
        self.adrs = sorted(adrs, key=lambda a: (id_key(a['alias']), a['stem']))

    def scan_archive(self):
        archive = os.path.join(self.vault, '04-Archive')
        self.archived = [self.load(p, require_fm=False) for p in walk_md(os.path.join(archive, 'Completed-Tasks'))]
        resolved = [self.load(p, require_fm=False) for p in walk_md(os.path.join(archive, 'Resolved-Bugs'))]
        late = [b for b in self.all_bugs if text_of(b['fm'].get('status')).lower() == 'archived']
        self.released = [n for n in self.archived + resolved + late if text_of(n['fm'].get('release_version'))]

    def scan_reports(self, dirs, pattern, require_fm):
        out = []
        for d in dirs:
            for f in sorted(os.listdir(d)) if os.path.isdir(d) else []:
                if not re.match(pattern, f):
                    continue
                n = self.load(os.path.join(d, f), require_fm=False)
                if not n['fm'] and require_fm:
                    self.warn('no frontmatter: %s (report not listed)' % self.rel(n['path']))
                    continue
                n['date'] = text_of(n['fm'].get('date')) or date_in(f)
                out.append(n)
        return sorted(out, key=lambda n: (n['date'], n['stem']), reverse=True)

    def scan_audits(self):
        found = {}
        for f in sorted(os.listdir(self.usage_dir)) if os.path.isdir(self.usage_dir) else []:
            m = re.match(r'^usage-audit-(\d{4}-\d{2}-\d{2})\.(md|json)$', f)
            if m:
                found.setdefault(m.group(1), {})[m.group(2)] = os.path.join(self.usage_dir, f)
        self.audits = []
        for date in sorted(found, reverse=True):
            e = found[date]
            data = None
            if 'json' in e:
                try:
                    with open(e['json'], encoding='utf-8-sig') as fh:
                        data = json.load(fh)
                    if not isinstance(data, dict):
                        raise ValueError('not a JSON object')
                except Exception as exc:
                    self.warn('unreadable usage-audit sidecar: %s (%s)' % (self.rel(e['json']), exc))
                    data = None
            text = None
            if 'md' in e:
                try:
                    text = read_text(e['md'])
                except OSError:
                    text = None
            since = text_of((data or {}).get('since'))
            if not since and text:
                m = re.search(r'window since (\d{4}-\d{2}-\d{2})', text[:600])
                since = m.group(1) if m else ''
            from_md = rule_status_from_report(text) if text else {}
            from_json = rule_status_from_sidecar(data, self.rules) if data else {}
            status = {r: from_md.get(r) or from_json.get(r) or 'n/a' for r in RULES}
            self.audits.append({'date': date, 'md': e.get('md') if text is not None else None, 'data': data, 'since': since,
                                'status': status, 'proposals': count_proposals(text) if text is not None else None})

    def scan_lock(self):
        path = os.path.join(self.root, '.it-department', 'lock.json')
        if not os.path.exists(path):
            return 'free'
        try:
            with open(path, encoding='utf-8-sig') as fh:
                lock = json.load(fh)
            if not isinstance(lock, dict):
                raise ValueError('not a JSON object')
        except Exception as e:
            self.warn('unreadable lock file: %s (%s)' % (self.rel(path), e))
            return 'unreadable `.it-department/lock.json`'

        def g(k):
            return text_of(lock.get(k)) or '?'
        text = '%s@%s since %s, expires %s' % (g('owner_role'), g('host'), g('started_at'), g('expires_at'))
        expires = parse_ts(lock.get('expires_at'))
        if expires is not None and expires < self.now.astimezone(datetime.timezone.utc):
            text += ' (expired)'
        return text

    # ----------------------------------------------------------------------- links
    def link(self, full, title=None, table=False):
        """Link to an existing file: wikilink when it is inside the vault and its name resolves, otherwise a
        markdown link relative to the dashboard (files outside the vault, hidden folders, unlinkable names)."""
        name = os.path.basename(full.rstrip('/\\'))
        target = name[:-3] if name.lower().endswith('.md') else name
        if inside(full, self.vault) and self.resolves(target):
            return wikilink(target, title, table)
        return '[%s](%s)' % (md_text(title or name, table), md_url(fwd(full, self.vault)))

    def doc(self, path, title=None, table=False, where=''):
        """(link text, exists) for a project-relative document path or URL; missing paths are warned."""
        path = path.strip()
        if re.match(r'^[A-Za-z][A-Za-z0-9+.-]*://', path):
            return '[%s](%s)' % (md_text(title or path, table), path), True
        full = path if os.path.isabs(path) else os.path.join(self.root, path)
        if not os.path.exists(full):
            self.warn('missing document: %s%s' % (path, (' (%s)' % where) if where else ''))
            return '%s (missing)' % code(path, table), False
        return self.link(full, title, table), True

    def note_link(self, n, alias=None):
        alias = alias or n['id']
        return self.link(n['path'], alias if alias != n['stem'] else None, table=True)

    def task_links(self, value, where):
        """Ids found in a parent_task / linked_task value -> wikilinks, or 'ID (missing)' when no note has that name."""
        text = text_of(value)
        ids, out = [], []
        for i in re.findall(r'\b[A-Z][A-Z0-9]*-\d+\b', text):
            if i not in ids:
                ids.append(i)
        for i in ids:
            if self.resolves(i):
                out.append('[[%s]]' % i)
            else:
                self.warn('unresolved link: %s (%s)' % (i, where))
                out.append('%s (missing)' % i)
        return ', '.join(out) if out else esc(text)

    def delink(self, text, where):
        """Safety net for VL006: a wikilink that does not resolve in the vault (e.g. typed into a title) is turned
        into its plain text; links inside code spans are left alone, as the lint ignores them."""
        def fix(m):
            target = link_target(m.group(1))
            if not target or self.resolves(target):
                return m.group(0)
            self.warn('unresolved wikilink [[%s]] shown as text (%s block)' % (m.group(1).replace('\\|', '|'), where))
            return link_label(m.group(1))
        out, pos = [], 0
        for m in INLINE_CODE_RE.finditer(text):
            out.append(WIKILINK_RE.sub(fix, text[pos:m.start()]) + m.group(0))
            pos = m.end()
        return ''.join(out) + WIKILINK_RE.sub(fix, text[pos:])

    # ----------------------------------------------------------------------- blocks
    def render_body(self):
        """Every block except the header, with unresolved wikilinks turned into text."""
        blocks = {'tokens': self.r_tokens(), 'kanban': self.r_kanban(), 'tasks': self.r_tasks(), 'bugs': self.r_bugs(),
                  'adr': self.r_adr(), 'usage-audits': self.r_usage(), 'content-reviews': self.r_reviews(),
                  'releases': self.r_releases(), 'documents': self.r_documents()}
        return dict((k, self.delink(v, k)) for k, v in blocks.items())

    def r_header(self, last_updated):
        name = text_of(self.cfg.get('project_name')) or os.path.basename(os.path.normpath(self.root)) or 'Project'
        journal = '[[decisions-log]]' if self.journal else 'decisions-log (missing)'
        return self.delink('\n'.join(['**Project:** %s  ' % name,
                                      '**Last Updated:** %s  ' % last_updated,
                                      '**Operating Profile:** %s (%s)  ' % (self.profile_text, journal),
                                      '**CTO Decision Mode:** %s  ' % (text_of(self.cfg.get('cto_mode')) or 'VIRTUAL'),
                                      '**Session Lock:** %s  ' % self.lock_text,
                                      '**Vault Archival Policy:** Active (Zero-Deletion Enforced)']), 'header')

    def r_tokens(self):
        if not self.audits:
            return 'No usage audit yet %s run usage_report.py' % DASH
        a = self.audits[0]
        link = self.link(a['md'], a['date']) if a['md'] else a['date']
        since = a['since'] or '?'
        d = a['data']
        if d is not None:
            prev = self.audits[1] if len(self.audits) > 1 else None
            if prev is None or prev['data'] is None:
                delta = 'baseline'
            else:
                delta = '%s vs previous' % delta_str(prev['data'].get('weighted_total'), d.get('weighted_total'))
            hours = d.get('jobs_hours')
            first = SEP.join(['Last audit %s (window since %s)' % (link, since),
                              'weighted tokens %s (%s)' % (number(d.get('weighted_total')), delta),
                              'output %s' % number(d.get('output_tokens')),
                              'jobs %s/%s h' % (number(d.get('jobs')), ('%.1f' % hours) if is_num(hours) else 'n/a'),
                              'screenshots %s' % number(d.get('screenshots_total'))])
        else:
            first = 'Last audit %s (window since %s)%snumbers n/a (no .json sidecar; re-run usage_report.py)' % (link, since, SEP)
        lines = [first, SEP.join('%s %s' % (r, a['status'][r]) for r in RULES),
                 'Proposals pending CTO decision: %s' % (a['proposals'][1] if a['proposals'] is not None else 'n/a')]
        day = parse_date(a['date'])
        if day is not None:
            due = day + datetime.timedelta(days=self.interval)
            lines.append('Next audit due: %s%s' % (due.isoformat(), ' (overdue)' if due < self.today else ''))
        return '  \n'.join(lines)

    def r_kanban(self):
        counts = dict((s, 0) for s in TASK_STATUSES)
        for t in self.tasks:
            if t['folder']:
                counts[t['folder']] += 1
        return '\n'.join(['| %s | Archived |' % ' | '.join(TASK_STATUSES),
                          '|' + ' :---: |' * (len(TASK_STATUSES) + 1),
                          '| %s | %d |' % (' | '.join(str(counts[s]) for s in TASK_STATUSES), len(self.archived))])

    def r_tasks(self):
        out = ['| Task ID | Title | Priority | Route | Assigned Agent | Branch | Status | Content review | QA | Docs |',
               '|' + ' :--- |' * 10]
        for t in self.tasks:
            fm = t['fm']
            review = 'n/a'
            if text_of(fm.get('content_review')).lower() == 'required':
                review = 'intake: %s' % (text_of(fm.get('content_review_intake')) or 'pending')
            out.append('| %s |' % ' | '.join([
                self.note_link(t), esc(t['title']), esc(fm.get('priority')), esc(fm.get('route')), esc(fm.get('assigned_agent')),
                code(fm.get('branch')), esc(t['status']), esc(review), esc(fm.get('qa_status')), self.docs_cell(t)]))
        if len(out) == 2:
            out.append('| *(No active tasks)* |' + ' |' * 9)
        return '\n'.join(out)

    def docs_cell(self, n):
        docs = n['fm'].get('docs')
        docs = docs if isinstance(docs, list) else ([docs] if text_of(docs) else [])
        links = [self.doc(text_of(d), table=True, where='%s docs' % n['id'])[0] for d in docs if text_of(d)]
        return ', '.join(links) if links else DASH

    def r_bugs(self):
        out = ['| Bug ID | Title | Severity | Category/Locale | Linked Task | Assigned Agent | Status | Blocking |',
               '|' + ' :--- |' * 8]
        for b in self.bugs:
            fm = b['fm']
            category = text_of(fm.get('category')) or text_of(fm.get('area'))
            locale = text_of(fm.get('locale'))
            linked = fm.get('parent_task') if text_of(fm.get('parent_task')) else fm.get('linked_task')
            blocking = fm.get('release_blocking')
            if isinstance(blocking, str):
                blocking = {'true': True, 'yes': True, 'false': False, 'no': False}.get(blocking.strip().lower(), blocking)
            out.append('| %s |' % ' | '.join([
                self.note_link(b), esc(b['title']), esc(fm.get('severity')),
                esc('%s/%s' % (category or DASH, locale) if locale else category),
                self.task_links(linked, '%s linked task' % b['id']) if text_of(linked) else DASH,
                esc(fm.get('assigned_agent')), esc(fm.get('status')),
                'yes' if blocking is True else ('no' if blocking is False else esc(blocking))]))
        if len(out) == 2:
            out.append('| *(Zero open defects)* |' + ' |' * 7)
        return '\n'.join(out)

    def r_adr(self):
        out = ['| ADR ID | Decision Title | Status | Date | Approver |', '|' + ' :--- |' * 5]
        for a in self.adrs:
            fm = a['fm']
            out.append('| %s | %s | %s | %s | %s |' % (self.note_link(a, a['alias']), esc(a['title']), esc(fm.get('status')),
                                                     esc(fm.get('date')), esc(fm.get('approver'))))
        if len(out) == 2:
            out.append('| *(No architectural decision records yet)* |' + ' |' * 4)
        return '\n'.join(out)

    def r_usage(self):
        out = ['| Date | Report | Window | Weighted tokens | Delta | Proposals (pending/total) | Rule flags |', '|' + ' :--- |' * 7]
        for i, a in enumerate(self.audits[:MAX_ROWS]):
            d = a['data']
            prev = self.audits[i + 1] if i + 1 < len(self.audits) else None
            if d is None:
                delta = 'n/a'
            elif prev is None or prev['data'] is None:
                delta = 'baseline'
            else:
                delta = delta_str(prev['data'].get('weighted_total'), d.get('weighted_total'))
            props = '%d/%d' % (a['proposals'][1], a['proposals'][0]) if a['proposals'] is not None else DASH
            flags = ' '.join(r for r in RULES if a['status'][r] == 'CHECK')
            out.append('| %s | %s | %s | %s | %s | %s | %s |' % (
                a['date'], self.link(a['md'], table=True) if a['md'] else DASH, ('since %s' % a['since']) if a['since'] else DASH,
                number(d.get('weighted_total')) if d else 'n/a', delta, props, flags or DASH))
        if len(out) == 2:
            out.append('| *(No usage audit yet %s the first one becomes the baseline)* |' % DASH + ' |' * 6)
        return '\n'.join(out)

    def r_reviews(self):
        out = ['| Date | Checkpoint | Scope | Locales | Findings C/M/m/T | Verdict | Report |', '|' + ' :--- |' * 7]
        for r in self.reviews[:MAX_ROWS]:
            fm = r['fm']
            f = inline_map(fm.get('findings'))
            findings = '/'.join(text_of(f.get(k, 0)) for k in ('critical', 'major', 'minor', 'trivial')) if f else DASH
            scope = text_of(fm.get('scope'))
            out.append('| %s | %s | %s | %s | %s | %s | %s |' % (
                esc(r['date']), esc(fm.get('checkpoint')), ('[[%s]]' % scope) if self.resolves(scope) else esc(scope),
                esc(fm.get('locales_reviewed')), findings, esc(fm.get('verdict')), self.link(r['path'], table=True)))
        if len(out) == 2:
            out.append('| *(No content review yet %s glossary and style guide live in `vault/06-Content/`)* |' % DASH + ' |' * 6)
        return '\n'.join(out)

    def verified_by(self, commit):
        sha7 = commit.strip().lower()[:7]
        if len(sha7) < 4:
            return None
        for q in self.qa:  # newest first
            if q['stem'].lower().endswith('-' + sha7) or text_of(q['fm'].get('candidate_sha')).lower().startswith(sha7):
                return self.link(q['path'], table=True)
        return None

    def r_releases(self):
        out = ['| Release Tag | Commit SHA | Date | Tasks Included | Verified By |', '|' + ' :--- |' * 5]
        groups = {}
        for n in self.released:
            g = groups.setdefault(text_of(n['fm'].get('release_version')), {'commits': [], 'dates': [], 'notes': []})
            commit = text_of(n['fm'].get('release_commit'))
            if commit and commit not in g['commits']:
                g['commits'].append(commit)
            when = text_of(n['fm'].get('archived_at') or n['fm'].get('date_archived') or n['fm'].get('date_resolved'))
            if when:
                g['dates'].append(when[:10])
            g['notes'].append(n)
        ordered = sorted(groups.items(), key=lambda kv: (max(kv[1]['dates']) if kv[1]['dates'] else '', id_key(kv[0])), reverse=True)
        for version, g in ordered[:MAX_ROWS]:
            verified = [v for v in (self.verified_by(c) for c in g['commits']) if v]
            out.append('| %s | %s | %s | %s | %s |' % (
                esc(version), ', '.join(code(c) for c in g['commits']) or DASH, max(g['dates']) if g['dates'] else DASH,
                ', '.join(self.note_link(n) for n in sorted(g['notes'], key=lambda n: id_key(n['id']))),
                ', '.join(verified) or DASH))
        if len(out) == 2:
            out.append('| *(No releases recorded yet)* |' + ' |' * 4)
        return '\n'.join(out)

    def r_documents(self):
        out = []
        docs = self.cfg.get('documents')
        for d in docs if isinstance(docs, list) else []:
            if not isinstance(d, dict) or not text_of(d.get('path')):
                continue
            path = text_of(d.get('path'))
            title = text_of(d.get('title')) or os.path.basename(path.rstrip('/\\')) or path
            link, ok = self.doc(path, title, where='config documents')
            out.append(('- %s %s %s' % (link, DASH, code(path, False))) if ok else ('- %s %s %s' % (title, DASH, link)))
        auto = [('Glossary', self.glossary, 'product terms per locale', self.content_enabled),
                ('Style guide', self.style_guide, 'writing rules per locale', self.content_enabled),
                ('Decisions journal', self.decisions_log, 'CTO decisions (D-NNN)', True)]
        for title, full, note, expected in auto:
            if os.path.exists(full):
                out.append('- %s %s %s' % (self.link(full, title), DASH, note))
            elif expected:
                self.warn('missing document: %s (%s)' % (self.rel(full), title.lower()))
                out.append('- %s %s %s (missing)' % (title, DASH, code(self.rel(full), False)))
        audit = next((a for a in self.audits if a['md']), None)
        if audit:
            out.append('- %s %s %s%s' % (self.link(audit['md'], 'Latest usage audit'), DASH, audit['date'],
                                          (', window since %s' % audit['since']) if audit['since'] else ''))
        else:
            out.append('- Latest usage audit %s none yet' % DASH)
        for title, reports, keys in (('Latest content review', self.reviews, ('checkpoint', 'scope')),
                                     ('Latest QA report', self.qa, ('scope',))):
            if not reports:
                out.append('- %s %s none yet' % (title, DASH))
                continue
            r = reports[0]
            what = ' '.join(x for x in [r['date']] + [text_of(r['fm'].get(k)) for k in keys] if x)
            verdict = text_of(r['fm'].get('verdict'))
            out.append('- %s %s %s%s' % (self.link(r['path'], title), DASH, what or r['stem'], (': ' + verdict) if verdict else ''))
        return '\n'.join(out)


# --------------------------------------------------------------------------- merging blocks into the file
def marker(name, which):
    return '<!-- sync:%s %s -->' % (name, which)


def find_block(text, name):
    """(start, end) offsets of the text between the markers, None when absent, 'broken' when unbalanced."""
    starts = list(re.finditer(r'<!--\s*sync:%s\s+start\s*-->' % re.escape(name), text))
    ends = list(re.finditer(r'<!--\s*sync:%s\s+end\s*-->' % re.escape(name), text))
    if not starts and not ends:
        return None
    if len(starts) != 1 or len(ends) != 1 or ends[0].start() < starts[0].end():
        return 'broken'
    return starts[0].end(), ends[0].start()


def heading_index(lines, pattern):
    """First '## ' heading (outside code fences) matching the pattern and not already followed by a block."""
    rx, fence = re.compile(pattern, re.I), False
    for i, line in enumerate(lines):
        if line.lstrip().startswith(('```', '~~~')):
            fence = not fence
            continue
        if fence or not re.match(r'^##[ \t]', line) or not rx.search(line[2:]):
            continue
        j = i + 1
        while j < len(lines) and not lines[j].strip():
            j += 1
        if j < len(lines) and ANY_START_RE.search(lines[j]):
            continue
        return i
    return None


def tip_index(lines):
    for i in range(len(lines) - 1, -1, -1):
        nxt = lines[i + 1] if i + 1 < len(lines) else ''
        if re.match(r'^\s*>\s*\[!TIP\]', lines[i], re.I) and 'obsidian' in (lines[i] + nxt).lower():
            return i
    return None


def insert_block(text, name, content, journal=True):
    """Insert a block into a dashboard that has no markers for it (a new section keeps its static lines only
    when journal is true, i.e. when [[decisions-log]] resolves in the vault)."""
    _name, heading, pattern, extra = SECTION[name]
    extra = extra if journal else ()
    block = [marker(name, 'start')] + content.split('\n') + [marker(name, 'end')]
    lines = text.split('\n')
    if name == 'header':
        idx = next((i for i, line in enumerate(lines) if line.startswith('# ')), None)
    else:
        idx = heading_index(lines, pattern)
    if idx is None and name == 'header':
        return '\n'.join(block + [''] + lines)
    if idx is not None:
        after = lines[idx + 1:]
        return '\n'.join(lines[:idx + 1] + [''] + block + ([''] if after and after[0].strip() else []) + after)
    section = [heading, ''] + block + list(extra)
    tip = tip_index(lines)
    if tip is not None:
        before = lines[:tip]
        if before and before[-1].strip():
            before.append('')
        return '\n'.join(before + section + ['', '---', ''] + lines[tip:])
    body = list(lines)
    while body and not body[-1].strip():
        body.pop()
    if body and body[-1].strip() != '---':
        body += ['', '---']
    return '\n'.join(body + [''] + section) + '\n'


def merge(text, blocks, journal=True):
    """-> (new text, inserted block names, block names with broken markers)."""
    inserted, broken = [], []
    for name in BLOCKS:
        span = find_block(text, name)
        if span is None:
            text = insert_block(text, name, blocks[name], journal)
            inserted.append(name)
        elif span == 'broken':
            broken.append(name)
        else:
            text = text[:span[0]] + '\n' + blocks[name] + '\n' + text[span[1]:]
    return text, inserted, broken


def last_updated_of(text):
    span = find_block(text, 'header')
    if not isinstance(span, tuple):
        return None
    m = re.search(r'^\*\*Last Updated:\*\*[ \t]*(.*?)[ \t]*$', text[span[0]:span[1]], re.M)
    return m.group(1) if m and m.group(1) else None


def skeleton(journal=True):
    """Dashboard layout with empty marker pairs (used when the vault template cannot be found)."""
    lines = [TITLE, '', NOTE, '', marker('header', 'start'), marker('header', 'end'), '', '---', '']
    for name, heading, _pattern, extra in SECTIONS[1:]:
        lines += [heading, '', marker(name, 'start'), marker(name, 'end')] + list(extra if journal else ()) + ['', '---', '']
    return '\n'.join(lines + list(TIP)) + '\n'


def template_text(journal=True):
    """Base text of a new dashboard: the vault template (its static decisions-journal line dropped when the
    journal does not resolve), or the built-in skeleton when the template is not reachable."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'assets', 'vault-template', DASHBOARD)
    try:
        text = read_text(path)
    except OSError:
        return skeleton(journal)
    return text if journal else text.replace('\n\n' + JOURNAL_LINE + '\n', '\n')


# --------------------------------------------------------------------------- main
def sync(root, check=False, quiet=False, out=None):
    """Regenerate (or with check=True only compare) the dashboard of the project at root; returns the exit code."""
    out = out or sys.stdout

    def say(msg):
        print(msg, file=out)
    root = os.path.abspath(root)
    d = Dashboard(root, load_config(root), _now())
    if not os.path.isdir(d.vault):
        print('dashboard_sync: vault not found: %s (check --root and paths.vault_relative_path)' % d.vault, file=sys.stderr)
        return 2
    d.scan()
    body = d.render_body()
    exists = os.path.isfile(d.path)
    current = read_text(d.path) if exists else ''
    base = current if exists else template_text(d.journal)
    old = last_updated_of(base)
    changed = True
    if exists and old:
        new, inserted, broken = merge(base, dict(body, header=d.r_header(old)), d.journal)
        changed = new != current
    if changed:
        new, inserted, broken = merge(base, dict(body, header=d.r_header(d.now.strftime('%Y-%m-%d %H:%M'))), d.journal)
    for name in broken:
        d.warn('block %s has unbalanced or duplicate sync markers - left unchanged' % name)
    stats = '(%d tasks, %d bugs, %d warnings)' % (len(d.tasks), len(d.bugs), len(d.warnings))
    if not quiet:
        if not exists:
            say('%s %s from the vault template' % ('would create' if check else 'creating', d.rel(d.path)))
        for name in inserted if exists else []:
            say('%s block %s' % ('would insert' if check else 'inserted', name))
        for w in d.warnings:
            say('warning: ' + w)
    if check:
        if changed and not quiet:
            diff = list(difflib.unified_diff(current.split('\n'), new.split('\n'), 'a/' + d.rel(d.path),
                                             'b/' + d.rel(d.path), lineterm=''))
            for line in diff[:DIFF_LIMIT]:
                say(line)
            if len(diff) > DIFF_LIMIT:
                say('... (%d more diff lines)' % (len(diff) - DIFF_LIMIT))
        say(d.path)
        say('dashboard: %s %s' % ('out of date' if changed else 'up to date', stats))
        return 1 if changed or broken else 0
    if changed:
        write_text(d.path, new)
    say(d.path)
    say('dashboard: %s %s' % ('updated' if changed else 'unchanged', stats))
    return 1 if broken else 0


def main(argv=None):
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(errors='replace')
        except Exception:
            pass
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--root', default=os.getcwd(), help='project root (holds .it-department/config.json)')
    ap.add_argument('--check', action='store_true', help='compare only; exit 1 when the dashboard is out of date')
    ap.add_argument('--quiet', action='store_true', help='print only the dashboard path and the summary line')
    a = ap.parse_args(argv)
    return sync(a.root, check=a.check, quiet=a.quiet)


if __name__ == '__main__':
    sys.exit(main())
